language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "5.7.1"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y imagemagick --fix-missing
  - sudo apt-get install -y ghostscript
  - sudo apt-get install -y poppler-utils

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  email:
    recipients:
      - reallookbaoxiao@gmail.com
      - david_ziyu@outlook.com
      - hlhr202@outlook.com
      - phanshiyu@gmail.com
      - sundychenya1018@yahoo.com
    on_success: always # default: change
    on_failure: always # default: always

after_success:
  - npm run coveralls